image: Visual Studio 2019

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet build src/Elmish.WPF -c Release

test_script:
  - cmd: dotnet test src/Elmish.WPF.Tests -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: O0k27BASO9sKX1fKtihfqzfNnvv2NHl5M9KNUuyuNGEDcOfqllJin1ujQuPKRZB+
    on:
      appveyor_repo_tag: true
