version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

environment:
  NUGET_KEY:
    secure: ZmAxRcwpr3xMuOXgn7SplJ9/QvSj1uPJ52HW9KuqzPrUdSinErdzn+4RKAnWfamj

cache:
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: 'deploy\*.nupkg'

build_script:
  - cmd: fake build

for:
  - branches:
      only:
        - /stable-.*/
    skip_branch_with_pr: true
    build_script:
      - cmd: fake build -t Publish
