version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

cache:
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: 'deploy\*.nupkg'

build_script:
  - cmd: fake build

deploy:
  - provider: NuGet
    api_key:
      secure: ZmAxRcwpr3xMuOXgn7SplJ9/QvSj1uPJ52HW9KuqzPrUdSinErdzn+4RKAnWfamj
    on:
      branch: /stable-.*/
